language: php
php:
- '5.6'
- '7'
before_script:
- phpenv config-add env/travis/php.ini
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source --dev
script:
- ./shell/ci-phpunit-code-coverage.sh
after_script:
- php bin/ocular code-coverage:upload --format=php-clover build/coverage.clover
